### ISSUE TITLE
File Notify Event causes internal files to be listed

### ISSUE THREAD

**Issue by harningt** [Pext/pext_module_pass#2]
The file notification watch for the ~/.password-store folder is triggered for the .git files, so until the module is reloaded / passwords are listed, files like .git/index and the like show up at the top

**Comment by TheLastProject** [comment]
Thanks for the report. I don't use pass with git myself, but from my testing this should fix it. If it doesn't, please reopen and I'll do more extensive testing.

**Comment by harningt** [comment]
Looks like I don't have permissions to reopen the ticket...
It doesn't catch files in deeper subdirectories of .git, perhaps if you split the entry on directory separators and checked if .git was one of the elements.
Ex: .git/objects/5e/5exxxx would split to [ '.git', 'objects', '5e', '5exxxx' ] and you could do checks there.

This would also be good for checking for ignored names, like .gpg-id that may show up in sub-folders to set different keys there.
Another file auto-added into the .password-store by pass in 'git' mode, is a top-level .gitattributes file.

So in the end it looks like we have:

Folders:

- .git

Files:

- .gpg-id
- .gitattributes
- .stfolder  (not sure what this is, but typically 'dot-files' shouldn't affect the file list.

... thinking this through... checking the pass source code reveals all 'dot-files' are ignored (for listing, tree is used which would require -a to follow/show dot-files... so this might be even easier... if any of the path elements are "hidden" (have a '.' in the front) then ignore them.

**Comment by TheLastProject** [comment]
I am a bit hesitant to ignore all dotfiles, because they become inaccessible through Pext then. On the command line you could always create Personal/.hidden and still access it by typing it correctly, but in Pext you can only open entries that are available in the list. Filtering out dotfiles should probably become an option, because I can imagine people may want to use it to not have certain passwords show up in Pext.

Looking through the content of several .git directories more, together with the comment "until the module is reloaded / passwords are listed, files like .git/index and the like show up at the top", filtering in the same way the originally created list is filtered should fix the issue, which is what I decided to do. If this still doesn't work correctly I'm going to have to actually use pass' git functionality.
